services:
  postgres:
    image: 'postgres:alpine'
    restart: always
    environment:
      - 'POSTGRES_DB=montrack'
      - 'POSTGRES_PASSWORD=hehehe'
      - 'POSTGRES_USER=shevaaa'
    ports:
      - '5432:5432'
  cache:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=hohoho
      - REDIS_PORT=6379
      - REDIS_DATABASES=16